---
- name: Provision Printer Pi
  hosts: printerpi
  become: true
  roles:
  - {role: common, tags: ["common"]}
  - {role: samba, tags: ["samba"]}
  - {role: usb-printer, tags: ["usb-printer"]}
  - {role: usb-static-ip, tags: ["usb-static-ip"]}
