---
- name: Provision Server Pi
  hosts: serverpi
  become: true
  roles:
  - {role: common, tags: ["common"]}
  - {role: serverpi, tags: ["serverpi"]}
  - {role: aria2, tags: ["aria2"]}
  - {role: nginx, tags: ["nginx"]}
  - {role: wiki-gym, tags: ["wiki-gym"]}
  - {role: wiki, tags: ["wiki"]}
  - {role: samba, tags: ["samba"]}
  - {role: transmission, tags: ["transmission"]}
  - {role: usb-drive, tags: ["usb-drive"]}
#  - {role: usb-static-ip, tags: ["usb-static-ip"]}
