---
- name: Install Samba
  apt: name=samba
       state=present

- name: Provision config
  copy: src=smb.conf
        dest=/etc/samba/
  notify: Restart Samba

- name: Enable service
  service: name={{item}}
           enabled=true
           state=started
  with_items:
  - smbd
  - nmbd
