---
- name: Provision Dhcpcd config (Static IP)
  blockinfile:
    path: /etc/dhcpcd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (STATIC-IP)"
    block: |
      interface eth0
      # First IP in Wifi Home: Network -> LAN -> DHCP Conditional Serving Pool (LAN3)
      static ip_address=192.168.100.21/24
      static routers=192.168.100.1
      static domain_name_servers=192.168.100.3 192.168.100.1 8.8.8.8 8.8.4.4
  notify: Restart Dhcpcd
