---
- name: Install Printer deps
  apt: name={{item}}
       state=present
  with_items:
  - cups
  - foomatic-db
  - foomatic-db-engine

- name: Provision CUPS config
  copy: src=cupsd.conf
        dest=/etc/cups/
  notify: Restart CUPS

- name: Enable service
  service: name=cups
           enabled=true
           state=started

- name: Provision Samba config
  blockinfile:
    path: /etc/samba/smb.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (USB-PRINTER)"
    block: |
      [printers]
        comment = All Printers
        browseable = no
        path = /var/spool/samba
        printable = yes
        guest ok = yes
        read only = yes
        create mask = 0700

      [print$]
        comment = Printer Drivers
        path = /var/lib/samba/printers
        browseable = yes
        read only = no
        guest ok = no
  notify: Restart Samba

###
# Manual setup
###

#
# Get HP LaserJet P1005 printer firmware
# sudo getweb P1005
# Restart Printer
#
# go to http://raspberrypi:631/admin
#
# Enable: 'Allow users to cancel any job (not just their own)' and save.
#
# Plug and switch on the Printer
# Press 'Add Printer'
# Select 'HP LaserJet P1005 (HP LaserJet P1005)'
# 'Continue'
# Enable 'Share This Printer'
# 'Continue'
# Choose default: 'HP LaserJet P1005 Foomatic/foo2xqx'
# 'Add Printer'
# 'Set Default Options'
# 'Print Test Page'
#
