---
- name: Add user to lpadmin groups
  user: name=pi
        groups=lpadmin
        append=yes

- name: Install Printer deps
  apt: name={{item}}
       state=present
  with_items:
  - cups
  - foomatic-db
  - foomatic-db-engine

- name: Provision CUPS config
  copy: src=cupsd.conf
        dest=/etc/cups/
  notify: Restart CUPS

- name: Enable service
  service: name=cups
           enabled=true
           state=started

- name: Provision Samba config
  blockinfile:
    path: /etc/samba/smb.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (USB-PRINTER)"
    block: |
      [printers]
        comment = All Printers
        browseable = no
        path = /var/spool/samba
        printable = yes
        guest ok = yes
        read only = yes
        create mask = 0700

      [print$]
        comment = Printer Drivers
        path = /var/lib/samba/printers
        browseable = yes
        read only = no
        guest ok = no
  notify: Restart Samba

###
# Manual setup
###

#
# 1. Plug and switch on the Printer
# 2. Get HP LJ P1005 firmware file
# sudo getweb P1005
# 3. Restart Printer
# 4. Go to http://printerpi:631/admin
# 5. Enable 'Allow users to cancel any job (not just their own)' and save.
# 6. Press 'Add Printer'
# 7. Select 'HP LaserJet P1005 (HP LaserJet P1005)'
# 8. 'Continue'
# 9. Enable 'Share This Printer'
# 10. 'Continue'
# 11. Choose default: 'HP LaserJet P1005 Foomatic/foo2xqx'
# 12. 'Add Printer'
# 13. 'Set Default Options'
# 14. 'Maintenance' -> 'Print Test Page'
#
