---
- name: Install pip deps
  pip: name={{item}}
       state=latest
  with_items:
  - youtube-dl

- name: Install apt deps
  apt: name={{item}}
       state=latest
  with_items:
  - expect
  - telnet
