---
- name: Install deps
  apt:
    name:
    - git
    - python3-pip
    state: latest

- name: Install pip deps
  pip:
    name:
    - virtualenv
    - youtube-dl
    state: latest

- name: Install apt deps
  apt:
    name:
    - expect
    - jq
    - telnet
    state: latest

- name: Provision Dhcpcd config (Static IP)
  blockinfile:
    path: /etc/dhcpcd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (STATIC-IP)"
    block: |
      interface eth0
      static ip_address=192.168.100.3/24
      static routers=192.168.100.1
      static domain_name_servers=127.0.0.1 192.168.100.1
  notify: Restart Dhcpcd

- name: LGWebOSRemote 1/3
  git: repo=https://github.com/klattimer/LGWebOSRemote
       dest=~/LGWebOSRemote/
       version=e6614df
       update=false
  register: lgtv

- name: LGWebOSRemote 2/3
  command: ./install.sh chdir=~/LGWebOSRemote/
  when: lgtv.changed

- name: LGWebOSRemote 3/3
  command: chmod +x lgtv.sh chdir=~/LGWebOSRemote/
  when: lgtv.changed

# Pair with TV
# ~/LGWebOSRemote/lgtv.sh auth <IP>

- name: Notify TV Cron Job 1/6
  cron:
    name: "Notify TV Sun-Thu 15"
    weekday: "0-4"
    minute: "15"
    hour: "21"
    job: "~/LGWebOSRemote/lgtv.sh notification 'Network is going down in 15 mins'"

- name: Notify TV Cron Job 2/6
  cron:
    name: "Notify TV Sun-Thu 5"
    weekday: "0-4"
    minute: "25"
    hour: "21"
    job: "~/LGWebOSRemote/lgtv.sh notification 'Network is going down in 5 mins'"

- name: Notify TV Cron Job 3/6
  cron:
    name: "Notify TV Sun-Thu 1"
    weekday: "0-4"
    minute: "29"
    hour: "21"
    job: "~/LGWebOSRemote/lgtv.sh notification 'Network is going down now'"

- name: Notify TV Cron Job 4/6
  cron:
    name: "Notify TV Fri-Sut 15"
    weekday: "5-6"
    minute: "45"
    hour: "21"
    job: "~/LGWebOSRemote/lgtv.sh notification 'Network is going down in 15 mins'"

- name: Notify TV Cron Job 5/6
  cron:
    name: "Notify TV Fri-Sut 5"
    weekday: "5-6"
    minute: "55"
    hour: "21"
    job: "~/LGWebOSRemote/lgtv.sh notification 'Network is going down in 5 mins'"

- name: Notify TV Cron Job 6/6
  cron:
    name: "Notify TV Fri-Sut 1"
    weekday: "5-6"
    minute: "59"
    hour: "21"
    job: "~/LGWebOSRemote/lgtv.sh notification 'Network is going down now'"
