---
- name: Install Aria2
  apt: name=aria2
       state=present

- name: Ensure Downloads dir
  file: path=/media/Transcend/Downloads
        state=directory

- name: Provision config (1/3)
  file: path={{item}}
        state=directory
  with_items:
  - /var/lib/aria2
  - /etc/aria2

- name: Provision config (2/3)
  file: path=/var/lib/aria2/session
        state=touch

- name: Provision config (3/3)
  copy: src=aria2.conf
        dest=/etc/aria2/
  notify: Restart Aria2

- name: Setup WebUI (1/2)
  git: repo=https://github.com/ziahamza/webui-aria2.git
       dest=/var/www/aria2
       version=fb9d758

- name: Setup WebUI (1/2)
  file: src=/var/www/aria2/docs
        dest=/var/www/aria2/aria2
        state=link

- name: Provision nginx
  copy: src=webui-aria2.conf
        dest=/etc/nginx/conf.d/server.d/
  notify: Restart Nginx

- name: Enable service (1/2)
  copy: src=aria2.service
        dest=/lib/systemd/system/

- name: Enable service (2/2)
  service: name=aria2
           enabled=true
           state=started
